### ISSUE TITLE
如何收敛思路？

### ISSUE THREAD

**Issue by kiaorahao** [kiaorahao/IA003BP#11]
几个角度：
- 他人： 资源方、教练、组员、往期项目、同期其他项目
- 课程要求：Get到多少知识点
- 项目管理：协同规则、项目计划、执行监控、反馈调优
- 项目需要：从泛而全到最终落地到最小可能行动
- 主题收敛：行业报告（结构、落地方向）+ 其他项目结构

**Comment by linfengisep** [comment]
### 信息分析二期BP：
开智学堂学科全局认识开源协作指南
如果你也有朝一日想要开一个书店
猫啸风云：汽车后市场之变
寸弘一瓢 尺树根深（从读一本神级专业书，到探索该领域知识图谱的实践）
抖音为何会火？短视频背后的秘密
谁是未来创造者（少儿编程）
香港四大词人
以上小且美，往深处挖，自然惊艳。

### Our BP:
人工智能（AI）技术在中国文化教育领域应用现状及展望初探
**关键词:** 人工智能，VR/AR/MR，中国文化(这个又是天大的领域),教育,现状,展望
个人认为，每一个领域单做信息量就非常大，况且把它们柔和在一起研究，复杂度成倍增加。

考虑到资方需求，可以考虑主题 **《用VR/AR描绘佛教故事》**？
（天主教的church都有彩窗，彩窗就是给古代那些不懂文字的人读的）

队长付出很多，但是请原谅我的直言不讳
待议

**Comment by kiaorahao** [comment]
前几天主要是学习项目协调，花费很大时间。经过这几天密集交流（组员、资源方、教练）+ review部分行业报告，想法比最开始清晰些。我们可以根据这个思路： 先去发散去找到一个高有趣度的可能会落地的产品-商业主体，然后基于这个最终收敛点，在学术主题依据可能的工作量和必要性进行同位词或者上位词扩展后研究。

@linfengisep 的思路非常犀利，爱死啦。哈哈。 **用VR/AR描绘佛教故事** 其实的确是初衷，如果大家能不排斥，回归到这个主题，自然是再好不过的了。

关于项目协同沟通原则，昨天看战略组讨论，挺受启发，我参考了加入到我们的[0. 协同原则](https://github.com/kiaorahao/IA003BP/blob/master/BP_Principles.md)  大家可以把自认为重要的给添加进去。
