### ISSUE TITLE
敏捷开发在BP中的使用

### ISSUE THREAD

**Issue by linfengisep** [kiaorahao/IA003BP#20]
# 敏捷开发Agile/scrum

## 1.制定product backlog（总任务清单）
根据产品需求，罗列出任务清单

## 2.sprint backlog
根据优先级和总工时，从product backlog移出一部分任务，构成一个sprint backlog。每个sprint一般为两周。
举例
backlog   进行中   完成
 任务1        任务4
 任务2
 任务3

## 3.迭代：Daily scum
每个成员在其余成员面前表述：昨天做了什么，今天做什么，遇到的障碍是什么

## 5.敏捷开发在BP中的套用
5.1 product backlog：[IA003BP/Report_TOC](https://github.com/kiaorahao/IA003BP/blob/master/Delivery_List/Report_TOC.md)
5.2 sprint backlog
由于时间紧迫，将所有的任务移出，构成一个sprint backlog。 参考[从路演到倒推BP实施？Issue #14 ](https://github.com/kiaorahao/IA003BP/issues/14)
5.3 daily scum
可以在[IA003BP/BP Monitor](https://github.com/kiaorahao/IA003BP/blob/master/BP%20Monitor.md)汇报进度，以便队员知道进度和队长把控。
5.4 Sprint review
复盘总结
路演评分就是终极review

写到最后，发现 @kiaorahao 已经在使用了这套开发方法了。

**Comment by kiaorahao** [comment]
谢谢 @linfengisep ，学习了，以敏捷开发的思想把我们项目的关键点都串了一遍，也是对BP项目工作策略的一次极好的交叉验证。

我试着从`可能的自我`角度串前面2个，前面2项是关于目标的，即希望的项目（product backlog）和期待的项目（sprint backlog）。后面2个是关于控制的，即节点的控制（Daily scum）和全盘的控制（Sprint review）。关于目标如果套用`可能的自我`再加一项恐惧的项目，也很契合孙子兵法的“做最坏的打算”的精髓，比如：

- 没有在deadline前交付报告
- 短板现象：某一位组员因为不可控因素没完成预定任务，导致整体项目出现短板，变成残次品
- 报告整合失败：主题不明确，思路不清晰
- 没有洞见：只是“文献综述”，VR的简单的现有知识罗列，典型企业一般性分析，没有价值点、套利点、惊喜时刻
- 没有开智范：自我感觉良好，却不符合开智优秀作品标准
- 路演不如预期：整体没有对BP做出很好的呈现，答辩环节准备不充足

**Comment by linfengisep** [comment]
对BP项目工作策略的一次极好的交叉验证+1。 同意，哈哈。你分析的很到位，咱们项目已经用上这个开发方式，说明你平时执行任务就是这个方法。
